language: android

# Utilisation du JDK8
jdk:
  - oraclejdk8

android:
    components:
        # Prérequis pour utilisation dernière version Android SDK tools
        - tools
        - platform-tools

        # Build tools requis par le projet
        - build-tools-25.0.1
        # Version du SDK pour compiler le projet
        - android-25

        # Dépôt supplémentaire requis pour avoir support-v4 & appcompat-v7 24.2.1
        - extra-android-m2repository

    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

# From https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/.travis.yml
before_install:
    - pwd
    - ls -la
    - wget http://services.gradle.org/distributions/gradle-3.3-bin.zip
    - unzip gradle-3.3-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH

script: gradle build connectedCheck --info