language: android

# Utilisation du JDK8
jdk:
  - oraclejdk8

android:
    components:
        - extra-android-m2repository
        - tools
        - build-tools-23.0.3
        - android-24

# Attribution des droits pour linux
before_install:
  - chmod +x gradlew

# Lancement du xrapper gradle + niveau info
script: ./gradlew build connectedCheck --info