language: android

# Utilisation du JDK8
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
  - openjdk8

android:
    components:
        # Prérequis pour utilisation dernière version Android SDK tools
        - tools
        - platform-tools

        # Build tools requis par le projet
        - build-tools-24.0.3
        # Version du SDK pour compiler le projet
        - android-24

        # Dépôt supplémentaire requis pour avoir support-v4 & appcompat-v7 24.2.1
        - extra-android-m2repository

    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

# Attribution des droits pour linux
before_install:
  - chmod +x gradlew

# Lancement du wrapper gradle + niveau info
script: ./gradlew build connectedCheck --info