language: android

android:
    components:
        # Version de Build-tools
        - build-tools-22.0.1

        # Version du SDK
        - android-22

        # Composants additionnels
        - extra-google-m2repository