language: android

# Utilisation du JDK8
jdk:
  - oraclejdk8

android:
  components:
    # Prérequis pour utilisation dernière version Android SDK tools
    - tools
    - platform-tools

    # Build tools requis par le projet
    - build-tools-29.0.2
    # Version du SDK pour compiler le projet
    - android-29

    # Dépôt supplémentaire requis pour avoir support-v4 & appcompat-v7 24.2.1
    - extra-android-m2repository

  licenses:
    - '.+'

# https://gradle.org/install/#manually
before_install:
  - wget https://downloads.gradle.org/distributions/gradle-5.6-bin.zip
  - unzip gradle-5.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.6
  - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - gradle -v
  - gradle build