language: android

# Utilisation du JDK8
jdk:
  - oraclejdk8

android:
    components:
        # Prérequis pour utilisation dernière version Android SDK tools
        - platform-tools
        - tools

        # Build tools requis par le projet
        - build-tools-23.0.3
        # Version du SDK pour compiler le projet
        - android-24


        #- extra-android-m2repository

# Attribution des droits pour linux
before_install:
  - chmod +x gradlew

# Lancement du xrapper gradle + niveau info
script: ./gradlew build connectedCheck --info